# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'progressAnimationTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for progressAnimationTest
  pod "MBCircularProgressBar"

  target 'progressAnimationTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'progressAnimationTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
