# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exGoogleMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for exGoogleMap

    pod 'GoogleMaps'
    pod 'GooglePlaces'

  target 'exGoogleMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exGoogleMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
