# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exZXing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for exZXing

  target 'exZXingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exZXingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
